main: routes.c lecturaEscritura.h floyd.h ventanasResolucion.h recepcionDatos.h cargarDatos.h
	gcc routes.c -o routes `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`

routes.c:

lecturaEscritura.h:

floyd.h:

ventanasResolucion.h:

recepcionDatos.h:

cargarDatos.h:

