main: reemplazo.c entanasResolucion.h recepcionDatos.h cargarDatos.h
	gcc reemplazo.c -o reemplazo `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`

reemplazo.c:

entanasResolucion.h:

recepcionDatos.h: 

cargarDatos.h:

