main: knapsack.c entanasResolucion.h recepcionDatos.h cargarDatos.h
	gcc knapsack.c -o knapsack `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`

knapsack.c:

entanasResolucion.h:

recepcionDatos.h: 

cargarDatos.h:

